import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { deepMerge, readJson, writeJson } from './fs-utils.js';
import type { InstallContext, Installer } from './types.js';

interface OpenCodeConfig {
  mcpServers?: Record<string, { command: string; args?: string[] }>;
  plugin?: string[];
}

function configRoot(): string {
  // Per OpenCode docs, the user-global config dir is ~/.config/opencode/.
  // We honor XDG_CONFIG_HOME if set.
  const xdg = process.env.XDG_CONFIG_HOME;
  return xdg ? join(xdg, 'opencode') : join(homedir(), '.config', 'opencode');
}

function configFile(): string {
  return join(configRoot(), 'opencode.json');
}

function pluginPath(): string {
  return join(configRoot(), 'plugins', 'cavemem.js');
}

// Legacy locations from earlier versions of this installer. Cleaned up on
// uninstall so users don't end up with stale files.
function legacyConfigFile(): string {
  return join(homedir(), '.opencode', 'config.json');
}

function pluginSource(nodeBin: string, cliPath: string): string {
  // OpenCode plugins are loaded as ESM modules. Each hook fires the cavemem
  // CLI in a detached child so the IDE never blocks. Args via stdin keep
  // the shell command short and avoid quoting issues for tool input/output.
  const NODE = JSON.stringify(nodeBin);
  const CLI = JSON.stringify(cliPath);
  return `// AUTO-GENERATED by cavemem installer. Do not edit by hand.
// Re-run \`cavemem install --ide opencode\` to refresh.
import { spawn } from 'node:child_process';

const NODE = ${NODE};
const CLI = ${CLI};

const callArgs = new Map();

function runHook(event, payload) {
  try {
    const child = spawn(NODE, [CLI, 'hook', 'run', event, '--ide', 'opencode'], {
      stdio: ['pipe', 'ignore', 'ignore'],
      detached: true,
    });
    child.on('error', () => {});
    child.stdin.on('error', () => {});
    child.stdin.end(JSON.stringify(payload));
    child.unref();
  } catch (_e) {
    // never block the IDE on a hook failure
  }
}

export const cavemem = async () => ({
  'session.created': async (input) => {
    runHook('session-start', { session_id: input?.sessionID ?? 'unknown', ide: 'opencode' });
  },
  'session.idle': async (input) => {
    runHook('stop', { session_id: input?.sessionID ?? 'unknown', ide: 'opencode' });
  },
  'tool.execute.before': async (input, output) => {
    if (input?.callID) callArgs.set(input.callID, output?.args);
  },
  'tool.execute.after': async (input, output) => {
    const args = input?.callID ? callArgs.get(input.callID) : undefined;
    if (input?.callID) callArgs.delete(input.callID);
    runHook('post-tool-use', {
      session_id: input?.sessionID ?? 'unknown',
      ide: 'opencode',
      tool_name: input?.tool ?? 'unknown',
      tool_input: args ?? null,
      tool_response: output?.output ?? output?.title ?? null,
    });
  },
});
`;
}

export const openCode: Installer = {
  id: 'opencode',
  label: 'OpenCode',
  async detect(_ctx): Promise<boolean> {
    return existsSync(configRoot()) || existsSync(join(homedir(), '.opencode'));
  },
  async install(ctx: InstallContext): Promise<string[]> {
    const messages: string[] = [];
    const cfgPath = configFile();
    const plugPath = pluginPath();

    const current = readJson<OpenCodeConfig>(cfgPath, {});
    // Merge mcpServers + ensure cavemem plugin is registered so OpenCode
    // auto-loads it. (Plugins in plugins/ also auto-load, but listing in
    // `plugin` makes intent explicit and survives plugin-dir overrides.)
    const pluginList = Array.from(
      new Set([...(current.plugin ?? []), 'file://./plugins/cavemem.js']),
    );
    const next = deepMerge<OpenCodeConfig>(current, {
      mcpServers: {
        // Spawn node explicitly — same EFTYPE concern as the other installers.
        cavemem: { command: ctx.nodeBin, args: [ctx.cliPath, 'mcp'] },
      },
    });
    next.plugin = pluginList;
    writeJson(cfgPath, next);
    messages.push(`wrote ${cfgPath}`);

    mkdirSync(join(configRoot(), 'plugins'), { recursive: true });
    writeFileSync(plugPath, pluginSource(ctx.nodeBin, ctx.cliPath), 'utf8');
    messages.push(`wrote ${plugPath}`);

    return messages;
  },
  async uninstall(_ctx): Promise<string[]> {
    const messages: string[] = [];
    const cfgPath = configFile();
    const plugPath = pluginPath();
    const legacy = legacyConfigFile();

    for (const path of [cfgPath, legacy]) {
      if (!existsSync(path)) continue;
      const current = readJson<OpenCodeConfig>(path, {});
      if (current.mcpServers) {
        delete current.mcpServers.cavemem;
        if (Object.keys(current.mcpServers).length === 0) delete current.mcpServers;
      }
      if (current.plugin) {
        current.plugin = current.plugin.filter((p) => !p.includes('cavemem'));
        if (current.plugin.length === 0) delete current.plugin;
      }
      writeJson(path, current);
      messages.push(`updated ${path}`);
    }

    if (existsSync(plugPath)) {
      const { rmSync } = await import('node:fs');
      rmSync(plugPath, { force: true });
      messages.push(`removed ${plugPath}`);
    }

    return messages;
  },
};
